#!/bin/bash

sudo apt-get update && sudo apt-get upgrade
sudo apt-get install gdebi
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo gdebi google-chrome-stable_current_amd64.deb
rm google-chrome-stable_current_amd64.deb
