#!/bin/bash
sudo apt-get install icedtea-8-plugin openjdk-8-jre
sudo apt-get install openjdk-8-jdk
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer

